apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-sync
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.sync.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            fsGroup: 101
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app: {{ .Release.Name }}
                  topologyKey: kubernetes.io/hostname
          containers:
            - name: rsync
              image: "{{ .Values.sync.image.repository }}:{{ .Values.sync.image.tag }}"
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
              command:
                - sh
                - -c
                - |
                  apk add --no-cache rsync && \
                  rsync -rltz --delete \
                    --timeout=300 \
                    --no-owner --no-group \
                    {{ .Values.sync.upstream }} \
                    /data/
              volumeMounts:
                - name: mirror-data
                  mountPath: /data
              resources:
                {{- toYaml .Values.resources.sync | nindent 16 }}
          volumes:
            - name: mirror-data
              persistentVolumeClaim:
                claimName: {{ .Release.Name }}-data
