{{- if eq .Values.sync.method "rsync" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-sync
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.rsync.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            fsGroup: 101
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app: {{ .Release.Name }}
                  topologyKey: kubernetes.io/hostname
          containers:
            - name: rsync
              image: "{{ .Values.rsync.image.repository }}:{{ .Values.rsync.image.tag }}"
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
              command:
                - sh
                - -c
                - |
                  rsync -rltv \
                    --delete-after --delete-excluded \
                    --progress \
                    --partial-dir=.rsync-partial \
                    --timeout=60 \
                    --contimeout=10 \
                    --no-owner --no-group \
                    --exclude='Nginx-Fancyindex-Theme-light/' \
                    --exclude='index.html' \
                    --exclude='.rsync-partial/' \
                    {{ .Values.rsync.upstream }} \
                    /data/
              volumeMounts:
                - name: mirror-data
                  mountPath: /data
              resources:
                {{- toYaml .Values.resources.rsync | nindent 16 }}
          volumes:
            - name: mirror-data
              persistentVolumeClaim:
                claimName: {{ .Release.Name }}-data
{{- end }}
