{{- if eq .Values.sync.method "syncthing" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-syncthing-config
  namespace: {{ .Release.Namespace }}
data:
  config.xml: |
    <configuration version="37">
      <folder id="{{ .Values.syncthing.folderID }}" label="cachyos-mirror" path="/var/syncthing/data"
              type="receiveonly" rescanIntervalS="3600" fsWatcherEnabled="true"
              fsWatcherDelayS="10" ignorePerms="true" autoNormalize="true">
        <minDiskFree unit="%">1</minDiskFree>
      </folder>
      <gui enabled="false" tls="false">
        <address>127.0.0.1:8384</address>
      </gui>
      <options>
        <globalAnnounceEnabled>{{ .Values.syncthing.globalAnnounce | default true }}</globalAnnounceEnabled>
        <localAnnounceEnabled>false</localAnnounceEnabled>
        <relaysEnabled>{{ .Values.syncthing.relaysEnabled | default true }}</relaysEnabled>
        <urAccepted>-1</urAccepted>
        <crashReportingEnabled>false</crashReportingEnabled>
        <autoUpgradeIntervalH>0</autoUpgradeIntervalH>
        <natEnabled>true</natEnabled>
      </options>
    </configuration>
{{- end }}
