---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: "https://vault.{{ .Values.externalDomain }}"
      path: "kv"
      version: "v2"
      auth:
        jwt:
          path: "jwt-{{ .Values.environment }}"
          role: "external-secrets"
          kubernetesServiceAccountToken:
            serviceAccountRef:
              name: "external-secrets-operator"
              namespace: external-secrets
            audiences:
              - "vault.{{ .Values.externalDomain }}"
