---
apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  spec:
    provider:
      vault:
        server: "https://vault.m1k.cloud:8200"
        path: "kv"
        version: "v2"
        auth:
          tokenSecretRef:
            name: "vault-token"
            key: "token"
            namespace: external-secrets
