apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-client-argocd
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: keycloak-client-argocd
    template:
      data:
        client_id: "{{ `{{ .client_id }}` }}"
        client_secret: "{{ `{{ .client_secret }}` }}"
  data:
    - secretKey: client_id
      remoteRef:
        key: /keycloak/clients/argocd
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: /keycloak/clients/argocd
        property: client_secret
