apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-client-headlamp
  namespace: headlamp
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: keycloak-client-headlamp
    template:
      data:
        OIDC_CLIENT_ID: "{{ `{{ .client_id }}` }}"
        OIDC_CLIENT_SECRET: "{{ `{{ .client_secret }}` }}"
        OIDC_ISSUER_URL: "https://keycloak.{{ .Values.externalDomain }}/realms/{{ .Values.keycloakRealmId }}"
        OIDC_SCOPES: "openid profile email"
        OIDC_CALLBACK_URL: "https://k8s.{{ .Values.internalDomain }}/oidc-callback"
  data:
    - secretKey: client_id
      remoteRef:
        key: /keycloak/clients/headlamp
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: /keycloak/clients/headlamp
        property: client_secret
