apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-ldap-bind
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: keycloak-ldap-bind
    template:
      data:
        password: "{{ `{{ .password }}` }}"
  data:
    - secretKey: password
      remoteRef:
        key: /lldap/shared
        property: lldap_admin_password
