apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-pg-app
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: keycloak-pg-app
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ `{{ .username }}` }}"
        password: "{{ `{{ .password }}` }}"
  data:
    - secretKey: username
      remoteRef:
        key: /keycloak
        property: db_app_user
    - secretKey: password
      remoteRef:
        key: /keycloak
        property: db_app_password
