apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vm-query
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: haproxy
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: vm-cert
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vm-query-placeholder
                port:
                  number: 8428
