apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .Values.L2Advertisement.name }}
  namespace: {{ .Values.namespace }}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.IPAddressPool.name }}
  namespace: {{ .Values.namespace }}
spec:
  addresses:
  - {{ .Values.IPAddressPool.addresses }}
