{{ if .Values.networkPolicy.enabled }}
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: coredns
spec:
  endpointSelector:
    matchLabels: {}
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s:k8s-app: coredns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
  ing
---
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "l7-egress-visibility"
spec:
  description: "L7 policy"
  endpointSelector: {}
  egress:
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "80"
              protocol: "TCP"
            - port: "443"
              protocol: "TCP"
          rules:
            http:
              - {}
---
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "
spec:
  description: "L7 policy"
  endpointSelector: {}
  ingress:
    - fromEntities:
        - world
    - toPorts:
        - ports:
            - port: "80"
              protocol: "TCP"
            - port: "443"
              protocol: "TCP"
          rules:
            http:
              - {}
---
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "haproxy-controller-egress-all"
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: haproxy-ingress
  egress:
    - toEndpoints:
      - {}
---
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "all-pods-egress-world"
spec:
  endpointSelector: {}
  egress:
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "80"
              protocol: "TCP"
            - port: "443"
              protocol: "TCP"
            - port: "53"
              protocol: "ANY"
{{- end }}
