apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: keycloak
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    haproxy-ingress.github.io/affinity: cookie
    haproxy-ingress.github.io/session-cookie-name: KC_ROUTE
    haproxy-ingress.github.io/session-cookie-strategy: insert
spec:
  ingressClassName: haproxy
  tls:
    - secretName: keycloak-cert
      hosts:
        - keycloak.{{ .Values.externalDomain }}
  rules:
    - host: keycloak.{{ .Values.externalDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak-service
                port:
                  number: 8080
