apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: {{ .Values.keycloakInstances }}
  image: {{ .Values.keycloakImage }}
  startOptimized: false
  hostname:
    hostname: keycloak.{{ .Values.externalDomain }}
  http:
    httpEnabled: true
  proxy:
    headers: xforwarded
  scheduling:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: keycloak
                app.kubernetes.io/managed-by: keycloak-operator
            topologyKey: kubernetes.io/hostname
  db:
    vendor: postgres
    host: keycloak-pg-rw.keycloak.svc
    port: 5432
    database: keycloak
    usernameSecret:
      name: keycloak-pg-app
      key: username
    passwordSecret:
      name: keycloak-pg-app
      key: password
  bootstrapAdmin:
    user:
      secret: keycloak-bootstrap-admin
  env:
    - name: JAVA_OPTS_APPEND
      value: "-Xms256m -Xmx384m"
  unsupported:
    podTemplate:
      spec:
        containers:
          - volumeMounts:
              - name: theme
                mountPath: /opt/keycloak/themes/m1k/login/theme.properties
                subPath: theme.properties
              - name: theme
                mountPath: /opt/keycloak/themes/m1k/login/resources/css/custom.css
                subPath: custom.css
        volumes:
          - name: theme
            configMap:
              name: keycloak-theme
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 1Gi
