image:
  repository: ghcr.io/ironashram/veeam-exporter
  tag: v0.1.1
  pullPolicy: IfNotPresent

veeam:
  url: https://vbr.m1k.cloud:9419
  tlsInsecure: true
  sessionTypes: AgentBackup,BackupJob,BackupCopyJob,ConfigurationBackup,EndpointBackup

credentialsSecret: veeam-exporter

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    memory: 128Mi
