apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: kube-system
spec:
  source:
    chart: cilium
    repoURL: https://helm.cilium.io
    targetRevision: 1.18.0-pre.2
  destination:
    name: in-cluster
    namespace: kube-system
  project: default
