apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-vip
  namespace: argocd
spec:
  source:
    chart: kube-vip
    repoURL: https://kube-vip.github.io/helm-charts
    targetRevision: 0.9.6
  destination:
    name: in-cluster
    namespace: kube-vip
  project: default
