apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-webhook-hetzner
  namespace: cert-manager
spec:
  source:
    chart: cert-manager-webhook-hetzner
    repoURL: https://vadimkim.github.io/cert-manager-webhook-hetzner
    targetRevision: 1.3.3
  destination:
    name: in-cluster
    namespace: cert-manager
  project: default
