apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: grafana-admin
    template:
      data:
        admin-user: "{{ `{{ .username }}` }}"
        admin-password: "{{ `{{ .password }}` }}"
  data:
    - secretKey: username
      remoteRef:
        key: "/monitoring"
        property: grafana_user
    - secretKey: password
      remoteRef:
        key: "/monitoring"
        property: grafana_password
