apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: veeam-exporter
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: veeam-exporter
  data:
    - secretKey: username
      remoteRef:
        key: "/veeam-exporter"
        property: username
    - secretKey: password
      remoteRef:
        key: "/veeam-exporter"
        property: password
