{{ if .Values.networkPolicy.enabled }}
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "allow-all-traffic"
spec:
  description: "Allow all cluster-wide traffic"
  endpointSelector: {}
  ingress:
    - fromEntities:
        - cluster
        - world
        - host
        - unmanaged
  egress:
    - toEntities:
        - cluster
        - world
        - host
        - unmanaged
{{- end }}
