{{ if .Values.networkPolicy.enabled }}
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "allow-all-with-l7-visibility"
spec:
  description: "Allow all cluster-wide traffic and enable L7 visibility for DNS and HTTP (port 80)"
  endpointSelector: {}
  ingress:
    - fromEntities:
        - cluster
        - world
        - host
        - unmanaged
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "3000"
              protocol: TCP
            - port: "8081"
              protocol: TCP
            - port: "8082"
              protocol: TCP
            - port: "9090"
              protocol: TCP
            - port: "9093"
              protocol: TCP
          rules:
            http:
              - {}
    - fromEntities:
        - cluster
        - world
        - host
        - unmanaged
  egress:
    - toEntities:
        - cluster
        - world
        - host
        - unmanaged
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
        - ports:
            - port: "80"
              protocol: TCP
            - port: "3000"
              protocol: TCP
            - port: "8081"
              protocol: TCP
            - port: "8082"
              protocol: TCP
            - port: "9090"
              protocol: TCP
            - port: "9093"
              protocol: TCP
          rules:
            http:
              - {}
    - toEntities:
        - cluster
        - world
        - host
        - unmanaged
{{- end }}
