apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cachyos-mirror
  namespace: argocd
  labels:
    app/cluster: "{{ .Values.environment }}"
    app/source: local
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/ironashram/{{ .Values.environment }}.git
    path: charts/cachyos-mirror
    targetRevision: main
    helm:
      valuesObject:
        sync:
          method: syncthing
        rsync:
          upstream: rsync://no.mirror.cx/cachyos/
          schedule: "*/30 * * * *"
        syncthing:
          folderID: "ogfcd-hynra"
          remoteDeviceIDs:
            - "RPPVJJS-JKRNOQS-ORA7HAP-XDX35QT-QWD5Q6D-6UB7OBG-T3JEF3N-MOH6XA3"
            - "TL4QQ6H-GP7ZF3O-VMCQN2X-Y5VPKYD-6VFMPMI-C5LSXQD-DYXAHKE-35XFTQX"
          relaysEnabled: false
        nodeSelector:
          node-role.kubernetes.io/control-plane: "true"
        storage:
          size: 250Gi
          storageClass: synology-csi-iscsi-custom
        ingress:
          enabled: true
          host: cachyos-mirror.{{ .Values.internalDomain }}
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            haproxy-ingress.github.io/health-check-interval: "5s"
            haproxy-ingress.github.io/health-check-rise-count: "2"
            haproxy-ingress.github.io/health-check-fall-count: "2"
            haproxy-ingress.github.io/config-backend: |
              server public cdn.cachyos.org:443 backup ssl ca-file @system-ca sni str(cdn.cachyos.org)
              http-request set-header Host cdn.cachyos.org if { nbsrv lt 2 }
        lagExporter:
          mirrorDomain: cachyos-mirror.{{ .Values.externalDomain }}
        extraIngresses:
          - name: external
            host: cachyos-mirror.{{ .Values.externalDomain }}
            annotations:
              haproxy-ingress.github.io/allowlist-source-range: 0.0.0.0/0
              cert-manager.io/cluster-issuer: letsencrypt-prod
              haproxy-ingress.github.io/health-check-interval: "5s"
              haproxy-ingress.github.io/health-check-rise-count: "2"
              haproxy-ingress.github.io/health-check-fall-count: "2"
              haproxy-ingress.github.io/config-backend: |
                server public cdn.cachyos.org:443 backup ssl ca-file @system-ca sni str(cdn.cachyos.org)
                http-request set-header Host cdn.cachyos.org if { nbsrv lt 2 }
            tls:
              secretName: cachyos-mirror-external-cert
  destination:
    name: in-cluster
    namespace: cachyos-mirror
