apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cachyos-mirror
  namespace: argocd
  labels:
    app/cluster: "{{ .Values.environment }}"
    app/source: local
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/ironashram/{{ .Values.environment }}.git
    path: charts/cachyos-mirror
    targetRevision: main
    helm:
      valuesObject:
        sync:
          upstream: rsync://nl.mirror.cx/cachyos/
          schedule: "0 */2 * * *"
        storage:
          size: 250Gi
          storageClass: synology-csi-iscsi-custom
        ingress:
          enabled: true
          host: cachyos-mirror.{{ .Values.internalDomain }}
        extraIngresses:
          - name: external
            host: cachyos-mirror.{{ .Values.externalDomain }}
            annotations:
              haproxy-ingress.github.io/allowlist-source-range: 0.0.0.0/0
              cert-manager.io/cluster-issuer: letsencrypt-prod
            tls:
              secretName: cachyos-mirror-external-cert
  destination:
    name: in-cluster
    namespace: cachyos-mirror
