apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    app/cluster: "{{ .Values.environment }}"
    app/source: upstream
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.19.3
    helm:
      valuesObject:
        crds:
          enabled: true
  destination:
    name: in-cluster
    namespace: cert-manager
