apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets
  namespace: argocd
  labels:
    app/cluster: "{{ .Values.environment }}"
    app/source: local
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/ironashram/{{ .Values.environment }}.git
    path: charts/ciulium-network-policy
    targetRevision: main
    helm:
      parameters:
        - name: networkPolicy.enabled
          value: false
  destination:
    name: in-cluster
    namespace: cilium-network-policy
