apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-coredns
  namespace: argocd
  labels:
    app/cluster: "{{ .Values.environment }}"
    app/source: upstream
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  source:
    chart: coredns
    repoURL: https://coredns.github.io/helm
    targetRevision: 1.42.1
    helm:
      valuesObject:
        deployment:
          enabled: true
        replicaCount: 3
        podDisruptionBudget:
          minAvailable: 1
        prometheus:
          service:
            clusterIP: {{ .Values.k8sClusterDNS }}
            enabled: true
            annotations:
              prometheus.io/scrape: "true"
              prometheus.io/port: "9153"
          monitor:
            enabled: true
        servers:
          - zones:
              - zone: .
                scheme: dns://
                use_tcp: true
            port: 53
            plugins:
              - name: errors
              - name: health
                configBlock: |-
                  lameduck 10s
              - name: ready
              - name: kubernetes
                parameters: cluster.local in-addr.arpa ip6.arpa
                configBlock: |-
                  pods insecure
                  fallthrough in-addr.arpa ip6.arpa
                  ttl 30
              - name: prometheus
                parameters: 0.0.0.0:9153
              - name: forward
                parameters: . /etc/resolv.conf
              - name: cache
                parameters: 30
              - name: loop
              - name: reload
              - name: loadbalance
  destination:
    name: in-cluster
    namespace: kube-system
