apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  labels:
    app.m1k.cloud/cluster: kub1k
    app.m1k.cloud/source: upstream
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.14.4
    helm:
      values: |
        certController:
          create: true
        webhook:
          create: true
  destination:
    name: in-cluster
    namespace: external-secrets
