apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-runner-scale-set-commstack
  namespace: argocd
  labels:
    app/cluster: "{{ .Values.environment }}"
    app/source: upstream
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Delete=false
    automated:
      prune: true
      selfHeal: false
  source:
    chart: gha-runner-scale-set
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: 0.11.0
    helm:
      valuesObject:
        githubConfigUrl: "https://github.com/ironashram/commstack"
        githubConfigSecret: "github-config-secret"
        containerMode:
          type: "kubernetes"
          kubernetesModeWorkVolumeClaim:
            accessModes: ["ReadWriteOnce"]
            storageClassName: "local-path"
            resources:
              requests:
                storage: 2Gi
        controllerServiceAccount:
          namespace: arc-runners
          name: gha-runner-scale-set-controller-gha-rs-controller
  destination:
    name: in-cluster
    namespace: arc-runners
