apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-runner-scale-set-kub1k
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  source:
    chart: gha-runner-scale-set
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: 0.8.3
    helm:
      values: |
        githubConfigUrl: "https://github.com/ironashram/kub1k"
        githubConfigSecret: "github-config-secret"
        controllerServiceAccount:
          namespace: arc-runners
          name: gha-runner-scale-set-controller-gha-rs-controller
        template:
          spec:
            initContainers:
            - name: init-dind-externals
              image: ghcr.io/actions/actions-runner:latest
              command: ["cp", "-r", "-v", "/home/runner/externals/.", "/home/runner/tmpDir/"]
              volumeMounts:
                - name: dind-externals
                  mountPath: /home/runner/tmpDir
            containers:
            - name: runner
              image: ghcr.io/actions/actions-runner:latest
              command: ["/home/runner/run.sh"]
              env:
                - name: DOCKER_HOST
                  value: unix:///run/docker/docker.sock
              volumeMounts:
                - name: work
                  mountPath: /home/runner/_work
                - name: dind-sock
                  mountPath: /run/docker
                  readOnly: true
                - name: kubeconfig
                  mountPath: /home/runner/.kube/config-files/kub1k.yaml
                  readOnly: true
            - name: dind
              image: docker:dind
              args:
                - dockerd
                - --host=unix:///run/docker/docker.sock
                - --group=$(DOCKER_GROUP_GID)
              env:
                - name: DOCKER_GROUP_GID
                  value: "123"
                - name: DOCKER_IPTABLES_LEGACY
                  value: "1"
              securityContext:
                privileged: true
              volumeMounts:
                - name: work
                  mountPath: /home/runner/_work
                - name: dind-sock
                  mountPath: /run/docker
                - name: dind-externals
                  mountPath: /home/runner/externals
            volumes:
            - name: work
              emptyDir: {}
            - name: dind-sock
              emptyDir: {}
            - name: dind-externals
              emptyDir: {}
            - name: kubeconfig
              secret:
                secretName: kub1k-kubeconfig
  destination:
    name: in-cluster
    namespace: arc-runners
