apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-runner-scale-set-controller
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  source:
    chart: gha-runner-scale-set-controller
    repoURL: ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
    targetRevision: 0.8.3
    helm:
      values: |
        flags:
          logLevel: debug
  destination:
    name: in-cluster
    namespace: arc-systems
