apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-runner-scale-set-m1k-cloud
  namespace: argocd
  labels:
    app.m1k.cloud/cluster: kub1k
    app.m1k.cloud/source: upstream
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Delete=false
    automated:
      prune: true
      selfHeal: false
  source:
    chart: gha-runner-scale-set
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: 0.10.1
    helm:
      values: |
        githubConfigUrl: "https://github.com/ironashram/hetzner"
        githubConfigSecret: "github-config-secret"
        containerMode:
          type: "kubernetes"
          kubernetesModeWorkVolumeClaim:
            accessModes: ["ReadWriteOnce"]
            storageClassName: "local-path"
            resources:
              requests:
                storage: 2Gi
        controllerServiceAccount:
          namespace: arc-runners
          name: gha-runner-scale-set-controller-gha-rs-controller
  destination:
    name: in-cluster
    namespace: arc-runners
