apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: haproxy-ingress
  namespace: argocd
  labels:
    app/cluster: "{{ .Values.environment }}"
    app/source: upstream
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  source:
    chart: haproxy-ingress
    repoURL: https://haproxy-ingress.github.io/charts
    targetRevision: 0.16.1
    helm:
      valuesObject:
        controller:
          ingressClass: haproxy
          ingressClassResource:
            enabled: true
            default: true
          replicaCount: 2
          minAvailable: 1
          podLabels:
            kub1k.io/workload-heavy: "true"
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app.kubernetes.io/name: haproxy-ingress
                  topologyKey: kubernetes.io/hostname
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              nodeTaintsPolicy: Honor
              nodeAffinityPolicy: Honor
              labelSelector:
                matchLabels:
                  kub1k.io/workload-heavy: "true"
          publishService:
            enabled: true
          config:
            allowlist-source-range: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
          metrics:
            enabled: true
          serviceMonitor:
            enabled: true
          logs:
            enabled: true
  destination:
    name: in-cluster
    namespace: haproxy-ingress
