apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
  labels:
    app/cluster: "{{ .Values.environment }}"
    app/source: upstream
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  sources:
    - chart: headlamp
      repoURL: https://kubernetes-sigs.github.io/headlamp/
      targetRevision: 0.40.1
      helm:
        valueFiles:
          - $values/apps/values-fix-headlamp.yaml
        valuesObject:
          ingress:
            enabled: true
            ingressClassName: haproxy
            hosts:
              - host: k8s.{{ .Values.internalDomain }}
                paths:
                  - path: /
                    type: ImplementationSpecific
            tls:
              - secretName: headlamp-cert
                hosts:
                  - k8s.{{ .Values.internalDomain }}
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
    - repoURL: https://github.com/ironashram/{{ .Values.environment }}.git
      targetRevision: HEAD
      ref: values
  destination:
    name: in-cluster
    namespace: headlamp
