apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-vip
  namespace: argocd
  labels:
    app/cluster: "{{ .Values.environment }}"
    app/source: upstream
spec:
  project: default
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
  source:
    chart: kube-vip
    repoURL: https://kube-vip.github.io/helm-charts
    targetRevision: 0.9.9
    helm:
      releaseName: kube-vip
      valuesObject:
        config:
          address: "{{ .Values.k8sEndpoint }}"
        env:
          vip_interface: "eth0"
          vip_arp: "true"
          cp_enable: "true"
          vip_leaderelection: "true"
          vip_leasename: "plndr-cp-lock"
          vip_leaseduration: "60"
          vip_renewdeadline: "40"
          vip_retryperiod: "5"
          lb_enable: "false"
          svc_enable: "false"
          lb_port: "6443"
          KUBERNETES_SERVICE_HOST: "127.0.0.1"
          KUBERNETES_SERVICE_PORT: "6443"
        nodeSelector:
          node-role.kubernetes.io/control-plane: "true"
  destination:
    name: in-cluster
    namespace: kube-vip
