apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-cr
  namespace: argocd
  labels:
    app/cluster: "{{ .Values.environment }}"
    app/source: local
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/ironashram/{{ .Values.environment }}.git
    path: charts/metallb-cr
    targetRevision: main
    helm:
      valuesObject:
        namespace: "metallb-system"
        L2Advertisement:
          name: "l2lb"
        IPAddressPool:
          name: "routable-pool"
          addresses: "{{ .Values.lbIpPool }}"
  destination:
    name: in-cluster
    namespace: metallb-system
