apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-cr
  namespace: argocd
  labels:
    app/cluster: "{{ .Values.environment }}"
    app/source: local
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/ironashram/{{ .Values.environment }}.git
    path: charts/metallb-cr
    targetRevision: main
  destination:
    name: in-cluster
    namespace: kube-system
