apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  source:
    chart: minio
    repoURL: https://charts.min.io
    targetRevision: 5.0.11
    helm:
      values: |
        resources:
          requests:
            memory: 1Gi
        buckets:
          - name: terraform-backend
            policy: public
            purge: false
            versioning: false
        consoleIngress:
          enabled: true
          hosts:
          - minio.console.lab.m1k.cloud
        drivesPerNode: 1
        ingress:
          enabled: true
          hosts:
          - minio.lab.m1k.cloud
        persistence:
          enabled: true
          storageClass: directpv-min-io
          accessMode: ReadWriteOnce
          size: 50Gi
        podDisruptionBudget:
          enabled: true
        pools: 1
        replicas: 3
        users:
        - accessKey: admin
          policy: consoleAdmin
  destination:
    name: in-cluster
    namespace: minio
