apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-adapter
  namespace: argocd
  labels:
    app.m1k.cloud/cluster: kub1k
    app.m1k.cloud/source: upstream
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  source:
    chart: prometheus-adapter
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 4.11.0
    helm:
      values: |
        prometheus:
          url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local
          port: 9090
        rules:
          resource:
            cpu:
              containerQuery: |
                sum by (<<.GroupBy>>) (
                  rate(container_cpu_usage_seconds_total{container!="",<<.LabelMatchers>>}[3m])
                )
              nodeQuery: |
                sum  by (<<.GroupBy>>) (
                  rate(node_cpu_seconds_total{mode!="idle",mode!="iowait",mode!="steal",<<.LabelMatchers>>}[3m])
                )
              resources:
                overrides:
                  node:
                    resource: node
                  namespace:
                    resource: namespace
                  pod:
                    resource: pod
              containerLabel: container
            memory:
              containerQuery: |
                sum by (<<.GroupBy>>) (
                  avg_over_time(container_memory_working_set_bytes{container!="",<<.LabelMatchers>>}[3m])
                )
              nodeQuery: |
                sum by (<<.GroupBy>>) (
                  avg_over_time(node_memory_MemTotal_bytes{<<.LabelMatchers>>}[3m])
                  -
                  avg_over_time(node_memory_MemAvailable_bytes{<<.LabelMatchers>>}[3m])
                )
              resources:
                overrides:
                  node:
                    resource: node
                  namespace:
                    resource: namespace
                  pod:
                    resource: pod
              containerLabel: container
            window: 3m
  destination:
    name: in-cluster
    namespace: monitoring

