apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 47.3.0
    helm:
      values: |
        alertmanager:
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
            - alertmanager.lab.m1k.cloud
        grafana:
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
            - grafana.lab.m1k.cloud
        prometheus:
          ingress:
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-staging
            enabled: true
            ingressClassName: nginx
            hosts:
            - prometheus.lab.m1k.cloud
            tls:
              hosts:
              - prometheus.lab.m1k.cloud
        prometheusOperator:
          admissionWebhooks:
            patch:
              enabled:
                false
  destination:
    name: in-cluster
    namespace: monitoring
