apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets
  namespace: argocd
  labels:
    app.m1k.cloud/cluster: kub1k
    app.m1k.cloud/source: local
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/ironashram/kub1k.git
    path: charts/secrets
    targetRevision: main
    helm:
      values: |
        environment: {{ .Values.environment }}
  destination:
    name: in-cluster
    namespace: external-secrets
