apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets
  namespace: argocd
  labels:
    app/cluster: "{{ .Values.environment }}"
    app/source: local
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/ironashram/{{ .Values.environment }}.git
    path: charts/secrets
    targetRevision: main
    helm:
      parameters:
        - name: environment
          value: "{{ .Values.environment }}"
        - name: internalDomain
          value: "{{ .Values.internalDomain }}"
        - name: externalDomain
          value: "{{ .Values.externalDomain }}"
  destination:
    name: in-cluster
    namespace: external-secrets
