apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: synology-csi
  namespace: argocd
  labels:
    app.m1k.cloud/cluster: kub1k
    app.m1k.cloud/source: upstream
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  source:
    chart: synology-csi
    repoURL: https://christian-schlichtherle.github.io/synology-csi-chart
    targetRevision: 0.10.1
    helm:
      values: |
        clientInfoSecret:
          name: client-info-secret
          create: false
        storageClasses:
          iscsi-delete:
            parameters:
              protocol: iscsi
              fsType: ext4
              location: /volume2
            reclaimPolicy: Delete
          nfs-delete:
            mountOptions:
              - vers=4.1
            parameters:
              protocol: nfs
              location: /volume2
              mountPermissions: "0777"
            reclaimPolicy: Delete
  destination:
    name: in-cluster
    namespace: synology-csi
