apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: synology-csi
  namespace: argocd
  labels:
    app/cluster: "{{ .Values.environment }}"
    app/source: upstream
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  source:
    chart: synology-csi
    repoURL: https://christian-schlichtherle.github.io/synology-csi-chart
    targetRevision: 0.10.1
    helm:
      valuesObject:
        images:
          plugin:
            tag: v1.2.0
          attacher:
            tag: v4.10.0
          nodeDriverRegistrar:
            tag: v2.15.0
          provisioner:
            tag: v5.3.0
          resizer:
            tag: v1.14.0
          snapshotter:
            tag: v8.3.0
        clientInfoSecret:
          name: client-info-secret
          create: false
        storageClasses:
          iscsi-custom:
            reclaimPolicy: Delete
            parameters:
              fsType: xfs
              location: /volume1
              protocol: iscsi
          iscsi-delete:
            disabled: true
          iscsi-retain:
            disabled: true
          nfs-delete:
            disabled: true
          nfs-retain:
            disabled: true
          smb-delete:
            disabled: true
          smb-retain:
            disabled: true
  destination:
    name: in-cluster
    namespace: synology-csi
