apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: synology-csi
  namespace: argocd
  labels:
    app/cluster: "{{ .Values.environment }}"
    app/source: upstream
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  source:
    chart: synology-csi
    repoURL: https://zebernst.github.io/synology-csi-talos
    targetRevision: 0.9.5-pre.4
    helm:
      valuesObject:
        clientInfoSecret:
          name: client-info-secret
          create: false
        storageClasses:
          default:
            reclaimPolicy: Delete
            parameters:
              fsType: ext4
              location: /volume2
  destination:
    name: in-cluster
    namespace: synology-csi
