apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: synology-csi
  namespace: argocd
  labels:
    app.m1k.cloud/cluster: kub1k
    app.m1k.cloud/source: upstream
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  source:
    chart: synology-csi
    repoURL: https://christian-schlichtherle.github.io/synology-csi-chart
    targetRevision: 0.9.10
    helm:
      values: |
        clientInfoSecret:
          name: client-info-secret
          create: false
        storageClasses:
          default:
            reclaimPolicy: Delete
            parameters:
              fsType: ext4
              location: /volume2
  destination:
    name: in-cluster
    namespace: synology-csi
