apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: synology-csi
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  source:
    path: .
    repoURL: https://github.com/christian-schlichtherle/synology-csi-chart.git
    targetRevision: 22e57740732f680d2f4a2ad8a6918b442b48dd1b
    helm:
      values: |
        clientInfoSecret:
          name: client-info-secret
        storageClasses:
          synology-iscsi-storage:
            reclaimPolicy: Retain
            parameters:
              fsType: ext4
              location: /volume2
  destination:
    name: in-cluster
    namespace: synology-csi
