apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  source:
    chart: trivy-operator
    repoURL: ghcr.io/aquasecurity/helm-charts
    targetRevision: 0.24.0
    helm:
      values: |
        operator:
          scanJobsConcurrentLimit: 1
          scanJobsRetryDelay: 180s
          scannerReportTTL: "72h"
          metricsFindingsEnabled: true
          metricsVulnIdEnabled: true
          exposedSecretScannerEnabled: true
          metricsExposedSecretInfo: true
          metricsConfigAuditInfo: true
          metricsRbacAssessmentInfo: true
          metricsInfraAssessmentInfo: true
          metricsImageInfo: true
          metricsClusterComplianceInfo: true
        trivy:
          severity: HIGH,CRITICAL
          slow: true
          resources:
            requests:
              cpu: 100m
              memory: 100M
            limits:
              cpu: 500m
              memory: 768M
        serviceMonitor:
          enabled: true
          namespace: monitoring
          labels:
            release: kube-prometheus-stack
  ignoreDifferences:
    - group: "*"
      kind: "ClusterComplianceReport"
      jsonPointers:
        - /spec
  destination:
    name: in-cluster
    namespace: trivy-system
