apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: argocd
  labels:
    app/cluster: "{{ .Values.environment }}"
    app/source: upstream
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  source:
    chart: trivy-operator
    repoURL: ghcr.io/aquasecurity/helm-charts
    targetRevision: 0.28.0
    helm:
      valuesObject:
        operator:
          scanJobsConcurrentLimit: 1
          scanJobsRetryDelay: 180s
          scannerReportTTL: "72h"
          metricsFindingsEnabled: true
          metricsVulnIdEnabled: true
          exposedSecretScannerEnabled: true
          metricsExposedSecretInfo: true
          metricsConfigAuditInfo: true
          metricsRbacAssessmentInfo: true
          metricsInfraAssessmentInfo: true
          metricsImageInfo: true
          metricsClusterComplianceInfo: true
        trivy:
          severity: HIGH,CRITICAL
          slow: true
          resources:
            requests:
              cpu: 100m
              memory: 100M
            limits:
              cpu: 500m
              memory: 768M
        serviceMonitor:
          enabled: true
  destination:
    name: in-cluster
    namespace: trivy-system
