apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-operator
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  source:
    chart: vault-operator
    repoURL: https://kubernetes-charts.banzaicloud.com
    targetRevision: 1.19.0
    helm:
      values: |
        monitoring:
          serviceMonitor:
            enabled: false
  destination:
    name: in-cluster
    namespace: vault
