apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  labels:
    app/cluster: "{{ .Values.environment }}"
    app/source: upstream
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  source:
    chart: velero
    repoURL: https://vmware-tanzu.github.io/helm-charts
    targetRevision: 11.1.1
    helm:
      valuesObject:
        image:
          tag: v1.17.1
        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.13.1
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /target
                name: plugins
        kubectl:
          image:
            repository: public.ecr.aws/bitnami/kubectl
            tag: latest
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
        configuration:
          backupStorageLocation:
            - name: default
              default: true
              provider: aws
              bucket: velero-offsite
              config:
                s3Url: https://r1-it.storage.cloud.it
                region: ""
                checksumAlgorithm: ""
                s3ForcePathStyle: true
          volumeSnapshotLocation:
            - name: default
              provider: aws
              defaultVolumesToFsBackup: true
        credentials:
          useSecret: true
          existingSecret: cloud-credentials
        schedules:
          kub1k-daily:
            schedule: "CRON_TZ=Europe/Rome 0 13 * * *"
            useOwnerReferencesInBackup: false
            skipImmediately: false
            paused: false
            template:
              defaultVolumesToFsBackup: true
              excludedNamespaces:
                - trivy-system
                - velero
              includeClusterResources: true
              includedNamespaces:
                - "*"
              includedResources:
                - "*"
              snapshotVolumes: true
              storageLocation: default
              ttl: 360h
        metrics:
          serviceMonitor:
            enabled: true
          prometheusRule:
            enabled: true
            spec:
              - alert: VeleroBackupFailed
                annotations:
                  message: Velero backup {{ $labels.schedule }} has failed
                expr: |-
                  velero_backup_last_status{schedule!=""} != 1
                for: 15m
                labels:
                  severity: warning
              - alert: VeleroBackupFailing
                annotations:
                  message: Velero backup {{ $labels.schedule }} has been failing for the last 12h
                expr: |-
                  velero_backup_last_status{schedule!=""} != 1
                for: 12h
                labels:
                  severity: critical
              - alert: VeleroNoNewBackup
                annotations:
                  message: Velero backup {{ $labels.schedule }} has not run successfully in the last 25h
                expr: |-
                  (
                  (time() - velero_backup_last_successful_timestamp{schedule!=""}) >bool (25 * 3600)
                  or
                  absent(velero_backup_last_successful_timestamp{schedule!=""})
                  ) == 1
                for: 1h
                labels:
                  severity: critical
              - alert: VeleroBackupPartialFailures
                annotations:
                  message: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} partialy failed backups
                expr: |-
                  rate(velero_backup_partial_failure_total{schedule!=""}[25m])
                    / rate(velero_backup_attempt_total{schedule!=""}[25m]) > 0.5
                for: 15m
                labels:
                  severity: warning
                annotations:
                  message: Velero backup {{ $labels.schedule }} has failed
                expr: |-
                  velero_backup_last_status{schedule!=""} != 1
                for: 15m
                labels:
                  severity: warning
              - alert: VeleroBackupFailing
                annotations:
                  message: Velero backup {{ $labels.schedule }} has been failing for the last 12h
                expr: |-
                  velero_backup_last_status{schedule!=""} != 1
                for: 12h
                labels:
                  severity: critical
              - alert: VeleroNoNewBackup
                annotations:
                  message: Velero backup {{ $labels.schedule }} has not run successfully in the last 25h
                expr: |-
                  (
                  (time() - velero_backup_last_successful_timestamp{schedule!=""}) >bool (25 * 3600)
                  or
                  absent(velero_backup_last_successful_timestamp{schedule!=""})
                  ) == 1
                for: 1h
                labels:
                  severity: critical
              - alert: VeleroBackupPartialFailures
                annotations:
                  message: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} partialy failed backups
                expr: |-
                  rate(velero_backup_partial_failure_total{schedule!=""}[25m])
                    / rate(velero_backup_attempt_total{schedule!=""}[25m]) > 0.5
                for: 15m
                labels:
                  severity: warning
        deployNodeAgent: true
  destination:
    name: in-cluster
    namespace: velero
