apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero-ui
  namespace: argocd
  labels:
    app/cluster: "{{ .Values.environment }}"
    app/source: upstream
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  source:
    chart: velero-ui
    repoURL: https://helm.otwld.com/
    targetRevision: 0.14.0
    helm:
      valuesObject:
        image:
          tag: "0.10.1"
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          className: haproxy
          hosts:
            - host: velero.{{ .Values.internalDomain }}
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: velero-ui-cert
              hosts:
                - velero.{{ .Values.internalDomain }}
        env:
          - name: BASIC_AUTH_USER
            valueFrom:
              secretKeyRef:
                name: velero-ui-auth
                key: username
          - name: BASIC_AUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: velero-ui-auth
                key: password
  destination:
    name: in-cluster
    namespace: velero-ui
