controller:
  ingressClass: haproxy
  ingressClassResource:
    enabled: true
    default: true
  replicaCount: 2
  minAvailable: 1
  metrics:
    enabled: true
  serviceMonitor:
    enabled: true
  logs:
    enabled: true
