{
 "title": "Commstack - HAProxy",
 "description": "HAProxy with Prometheus data",
 "tags": [
  "haproxy",
  "servers"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(haproxy_process_nbproc{job=\"commstack-haproxy\"}, instance)"
    }
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": {
     "query": "label_values(haproxy_backend_status{job=\"commstack-haproxy\",instance=\"$host\"}, proxy)"
    }
   },
   {
    "name": "frontend",
    "label": "Frontend",
    "query": {
     "query": "label_values(haproxy_frontend_status{job=\"commstack-haproxy\",instance=\"$host\"}, proxy)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(haproxy_server_status{job=\"commstack-haproxy\",instance=\"$host\"}, server)"
    }
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": {
     "query": "label_values(haproxy_server_http_responses_total{job=\"commstack-haproxy\",instance=\"$host\"}, code)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  { "title": "Basic General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP response / request",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_http_responses_total{proxy=~\"$frontend\",code=~\"$code\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])) by (code)",
     "legendFormat": "Front {{ code }}"
    },
    {
     "expr": "sum(rate(haproxy_backend_http_responses_total{proxy=~\"$backend\",code=~\"$code\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])) by (code)",
     "legendFormat": "Back {{ code }}"
    },
    {
     "expr": "sum(rate(haproxy_frontend_http_requests_total{proxy=~\"$frontend\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Front requests"
    },
    {
     "expr": "sum(rate(haproxy_backend_http_requests_total{proxy=~\"$backend\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Back requests"
    }
   ]
  },
  {
   "title": "Front - Data transfer",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_bytes_in_total{proxy=~\"$frontend\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])*8) by (instance)",
     "legendFormat": "IN Front"
    },
    {
     "expr": "sum(rate(haproxy_frontend_bytes_out_total{proxy=~\"$frontend\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])*8) by (instance)",
     "legendFormat": "OUT Front"
    }
   ]
  },
  {
   "title": "Back - Data transfer",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_bytes_in_total{proxy=~\"$backend\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])*8) by (instance)",
     "legendFormat": "IN Back"
    },
    {
     "expr": "sum(rate(haproxy_backend_bytes_out_total{proxy=~\"$backend\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])*8) by (instance)",
     "legendFormat": "OUT Back"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_sessions_total{proxy=~\"$frontend\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Front"
    },
    {
     "expr": "sum(rate(haproxy_backend_sessions_total{proxy=~\"$backend\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Back"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_connections_total{proxy=~\"$frontend\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Front"
    },
    {
     "expr": "sum(rate(haproxy_backend_connection_attempts_total{proxy=~\"$backend\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Back"
    }
   ]
  },
  {
   "title": "Status UP",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 22, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(haproxy_frontend_status{job=\"commstack-haproxy\",instance=\"$host\",state=\"UP\"} == 1)",
     "legendFormat": "Front Up"
    },
    {
     "expr": "sum(haproxy_backend_status{job=\"commstack-haproxy\",instance=\"$host\",state=\"UP\"} ==1)",
     "legendFormat": "Back Up"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - haproxy_process_start_time_seconds{job=\"commstack-haproxy\",instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Requests / Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Front - HTTP requests Total / Error / Denied",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 16203 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_http_requests_total{proxy=~\"$frontend\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_frontend_request_errors_total{proxy=~\"$frontend\", job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Error {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_frontend_requests_denied_total{proxy=~\"$frontend\", job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - HTTP requests Total / Denied",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 16203 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_http_requests_total{proxy=~\"$backend\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_backend_requests_denied_total{proxy=~\"$backend\", job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - HTTP responses",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 19191 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_frontend_http_responses_total{proxy=~\"$frontend\", code=~\"$code\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])) by (proxy)",
       "legendFormat": "{{ proxy }} "
      }
     ]
    },
    {
     "title": "Back - HTTP responses",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 19191 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_backend_http_responses_total{proxy=~\"$backend\", code=~\"$code\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])) by (proxy)",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - HTTP responses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19204 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_server_http_responses_total{proxy=~\"$backend\",server=~\"$server\",code=~\"$code\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])) by (proxy, server)",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Front - HTTP responses code",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 19212 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_http_responses_total{proxy=~\"$frontend\", code=~\"$code\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ code }} {{ proxy }} "
      }
     ]
    },
    {
     "title": "Back - HTTP responses code",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 19212 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_http_responses_total{proxy=~\"$backend\", code=~\"$code\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ code }} {{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - HTTP responses code",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19225 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_http_responses_total{proxy=~\"$backend\",server=~\"$server\",code=~\"$code\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ code }} - {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Front - HTTP responses denied",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 19234 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_responses_denied_total{proxy=~\"$frontend\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - HTTP responses denied",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 19234 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_responses_denied_total{proxy=~\"$backend\", job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - HTTP responses denied",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19248 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_responses_denied_total{proxy=~\"$backend\", job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Back - Error / Redispatch / Retry",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 19257 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_redispatch_warnings_total{proxy=~\"$backend\", job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Redispatch {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_backend_retry_warnings_total{proxy=~\"$backend\", job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Retry {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_backend_response_errors_total{proxy=~\"$backend\", job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Error {{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Error / Redispatch / Retry",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19271 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_redispatch_warnings_total{proxy=~\"$backend\",server=~\"$server\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Redispatch {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(haproxy_server_retry_warnings_total{proxy=~\"$backend\",server=~\"$server\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Retry {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(haproxy_server_response_errors_total{proxy=~\"$backend\",server=~\"$server\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Error {{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Throughput / Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Front - Data transfer",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 16204 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_bytes_in_total{proxy=~\"$frontend\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "IN {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_frontend_bytes_out_total{proxy=~\"$frontend\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "OUT {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Data transfer",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 16204 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_bytes_in_total{proxy=~\"$backend\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "IN {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_backend_bytes_out_total{proxy=~\"$backend\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "OUT {{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Data transfer",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19193 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_bytes_in_total{proxy=~\"$backend\",server=~\"$server\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "IN {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(haproxy_server_bytes_out_total{proxy=~\"$backend\",server=~\"$server\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "OUT {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Front - Connections Accepted / Denied",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 19200 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_connections_total{proxy=~\"$frontend\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Accepted {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_frontend_denied_connections_total{proxy=~\"$frontend\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Connections Attempts / Errors",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 19200 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_connection_attempts_total{proxy=~\"$backend\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Attempt {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_backend_connection_errors_total{proxy=~\"$backend\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Error {{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Connections Attempts / Error",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19215 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_connection_attempts_total{proxy=~\"$backend\",server=~\"$server\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Attempts {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(haproxy_server_connection_errors_total{proxy=~\"$backend\",server=~\"$server\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Error {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Back - Connections reuses",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 19222 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_connection_reuses_total{proxy=~\"$backend\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Connections reuses",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19237 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_connection_reuses_total{proxy=~\"$backend\",server=~\"$server\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Reuses {{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Front - Sessions",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_sessions_total{proxy=~\"$frontend\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_frontend_denied_sessions_total{proxy=~\"$frontend\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Sessions",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_sessions_total{proxy=~\"$backend\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total {{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Session",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_sessions_total{proxy=~\"$backend\",server=~\"$server\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Front - Session usage",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max_over_time(haproxy_frontend_current_sessions{proxy=~\"$frontend\", job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval]) / haproxy_frontend_limit_sessions{proxy=~\"$frontend\", instance=\"$host\"} * 100",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Session usage",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max_over_time(haproxy_backend_current_sessions{proxy=~\"$backend\", job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval]) / haproxy_backend_limit_sessions{proxy=~\"$backend\", instance=\"$host\"} * 100",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Sessions Max",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "haproxy_frontend_max_sessions{proxy=~\"$frontend\",job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Sessions Max",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "haproxy_backend_max_sessions{proxy=~\"$backend\",job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Session Max",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "haproxy_server_max_sessions{proxy=~\"$backend\",server=~\"$server\",job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Front - Failed HTTP header rewrites",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_failed_header_rewriting_total{proxy=~\"$frontend\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Failed HTTP header rewrites",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_failed_header_rewriting_total{proxy=~\"$backend\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Failed HTTP header rewrites",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_failed_header_rewriting_total{proxy=~\"$backend\",server=~\"$server\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} /  {{ server }}"
      }
     ]
    },
    {
     "title": "Back -  Data transfers aborted",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_client_aborts_total{proxy=~\"$backend\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Client {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_backend_server_aborts_total{proxy=~\"$backend\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Server {{ proxy }}"
      }
     ]
    },
    {
     "title": "Server -  Data transfers aborted",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_client_aborts_total{proxy=~\"$backend\",server=~\"$server\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Client {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(haproxy_server_server_aborts_total{proxy=~\"$backend\",server=~\"$server\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Server {{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Back - Average connection time",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_backend_connect_time_average_seconds{proxy=~\"$backend\",job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Average total conn. time",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_backend_total_time_average_seconds{proxy=~\"$backend\",job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Average connection time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 720 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_server_connect_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Average total conn. time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 727 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_server_total_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Back - Average response time",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 734 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_backend_response_time_average_seconds{proxy=~\"$backend\",job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Average queue time",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 734 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_backend_queue_time_average_seconds{proxy=~\"$backend\",job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Average response time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 748 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_server_response_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Average queue time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 755 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_server_queue_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Health and Weight",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Back - UP->DOWN transitions",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_check_up_down_total{proxy=~\"$backend\", job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Service weight",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_backend_weight{proxy=~\"$backend\", job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      },
      {
       "expr": "haproxy_backend_uweight{proxy=~\"$backend\", job=\"commstack-haproxy\",instance=\"$host\"} - haproxy_backend_weight{proxy=~\"$backend\", instance=\"$host\"}",
       "legendFormat": "User diff - {{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - UP->DOWN transitions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_check_up_down_total{proxy=~\"$backend\",server=~\"$server\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Service weight",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_server_weight{proxy=~\"$backend\",server=~\"$server\",job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      },
      {
       "expr": "haproxy_server_uweight{proxy=~\"$backend\",server=~\"$server\",job=\"commstack-haproxy\",instance=\"$host\"} - haproxy_server_weight{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "User diff - {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Checks failures",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 159 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_check_failures_total{proxy=~\"$backend\",server=~\"$server\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Checks duration",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 166 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_server_check_duration_seconds{proxy=~\"$backend\",server=~\"$server\",job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Last session assigned",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 173 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_server_last_session_seconds{proxy=~\"$backend\", server=~\"$server\",job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache / Compressor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Front - Cache Lookups / Hits",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16208 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_http_cache_lookups_total{proxy=~\"$frontend\", job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Lookups {{ proxy }} "
      },
      {
       "expr": "rate(haproxy_frontend_http_cache_hits_total{proxy=~\"$frontend\", job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Hits {{ proxy }} "
      }
     ]
    },
    {
     "title": "Back - Cache Lookups / Hits",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16208 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_http_cache_lookups_total{proxy=~\"$backend\", job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Lookups {{ proxy }} "
      },
      {
       "expr": "rate(haproxy_backend_http_cache_hits_total{proxy=~\"$backend\", job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Hits {{ proxy }} "
      }
     ]
    },
    {
     "title": "Front - Data transfer http compressor",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16478 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_http_comp_bytes_in_total{proxy=~\"$frontend\", job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "IN {{ proxy }} "
      },
      {
       "expr": "rate(haproxy_frontend_http_comp_bytes_out_total{proxy=~\"$frontend\", job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "OUT {{ proxy }} "
      },
      {
       "expr": "rate(haproxy_frontend_http_comp_bytes_bypassed_total{proxy=~\"$frontend\", job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "Bypass  {{ proxy }} "
      }
     ]
    },
    {
     "title": "Back - Data transfer http compressor",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16478 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_http_comp_bytes_in_total{proxy=~\"$backend\", job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "IN {{ proxy }} "
      },
      {
       "expr": "rate(haproxy_backend_http_comp_bytes_out_total{proxy=~\"$backend\", job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "OUT {{ proxy }} "
      },
      {
       "expr": "rate(haproxy_backend_http_comp_bytes_bypassed_total{proxy=~\"$backend\", job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "Bypass  {{ proxy }} "
      }
     ]
    },
    {
     "title": "Front - Responses compressed",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16489 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_http_comp_responses_total{proxy=~\"$frontend\", job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} "
      }
     ]
    },
    {
     "title": "Back - Responses compressed",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16489 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_http_comp_responses_total{proxy=~\"$backend\", job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} "
      }
     ]
    }
   ]
  },
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Front - Status",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16209 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      {
       "expr": "haproxy_frontend_status{proxy=~\"$frontend\",job=\"commstack-haproxy\",instance=\"$host\",state=\"UP\"}",
       "legendFormat": "{{ proxy }} "
      }
     ]
    },
    {
     "title": "Back - Status",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16209 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      {
       "expr": "haproxy_backend_status{proxy=~\"$backend\",job=\"commstack-haproxy\",instance=\"$host\",state=\"UP\"}",
       "legendFormat": "{{ proxy }} "
      }
     ]
    },
    {
     "title": "Server - Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16338 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      {
       "expr": "haproxy_server_status{proxy=~\"$backend\",server=~\"$server\",job=\"commstack-haproxy\",instance=\"$host\",state=\"UP\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Status other",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16346 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "haproxy_server_status{proxy=~\"$backend\",server=~\"$server\",job=\"commstack-haproxy\",instance=\"$host\",state!~\"UP|DOWN\"}",
       "legendFormat": "{{ proxy }} / {{ server }} - {{state}}"
      }
     ]
    },
    {
     "title": "Front - Internal errors",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16354 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_internal_errors_total{proxy=~\"$frontend\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Internal errors",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16354 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_internal_errors_total{proxy=~\"$backend\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Internal errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16365 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_internal_errors_total{proxy=~\"$backend\",job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Sticktable usage",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16372 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_sticktable_size{proxy=~\"$backend\",job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      },
      {
       "expr": "haproxy_sticktable_used{proxy=~\"$backend\",job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Active servers",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16372 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_backend_active_servers{proxy=~\"$backend\",job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Backup servers",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16383 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_backend_backup_servers{proxy=~\"$backend\",job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process - Connection rate limits",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 7259 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_max_connection_rate{job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "Highest ConnRate reached on this worker process since started (in connections per second)"
      },
      {
       "expr": "haproxy_process_limit_connection_rate{job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "Hard limit for ConnRate (global.maxconnrate)"
      }
     ]
    },
    {
     "title": "Process - Connections limits",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 7259 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_current_connections{job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "Current number of connections on this worker process"
      },
      {
       "expr": "haproxy_process_hard_max_connections{job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "Hard limit on the number of per-process connections (imposed by Memmax_MB or ulimit -n)"
      }
     ]
    },
    {
     "title": "Process - Sessions limits",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 7259 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_max_session_rate{job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "Highest SessRate reached on this worker process since started (in sessions per second)"
      },
      {
       "expr": "haproxy_process_limit_session_rate{job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "Hard limit for SessRate (global.maxsessrate)"
      }
     ]
    },
    {
     "title": "Process - SSL conn. rate limits",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 7269 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_max_ssl_rate{job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "Highest ConnRate reached on this worker process since started (in connections per second)"
      },
      {
       "expr": "haproxy_process_limit_ssl_rate{job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "Hard limit for SslRate (global.maxsslrate)"
      }
     ]
    },
    {
     "title": "Process - SSL conn. limits",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 7269 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_current_ssl_connections{job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "SSL endpoints"
      },
      {
       "expr": "haproxy_process_max_ssl_connections{job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "Hard limit  SSL endpoints"
      }
     ]
    },
    {
     "title": "Process - SSL key rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 7269 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "haproxy_process_current_frontend_ssl_key_rate{job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "SSL keys created on frontends"
      },
      {
       "expr": "haproxy_process_current_backend_ssl_key_rate{job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "SSL keys created on backend"
      }
     ]
    },
    {
     "title": "Process - SSL cache",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 7279 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(haproxy_process_ssl_cache_lookups_total{job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Lookups"
      },
      {
       "expr": "rate(haproxy_process_ssl_cache_misses_total{job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Miss"
      },
      {
       "expr": "rate(haproxy_process_ssl_connections_total{job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "SSL Connections"
      }
     ]
    },
    {
     "title": "Process - SSL reuse ratio",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 7279 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "haproxy_process_frontend_ssl_reuse{job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "Frontend SSL connections which did not require a new key"
      }
     ]
    },
    {
     "title": "Process - Zlib (HTTP compression) memory limits",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 7279 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_current_zlib_memory{job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "Amount of memory currently used by HTTP compression"
      },
      {
       "expr": "haproxy_process_max_zlib_memory{job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "Limit memory used by HTTP compression,  above is auto disabled (in bytes, see global.maxzlibmem)"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process - Failed DNS resolutions",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 7260 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(haproxy_process_failed_resolutions{job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total number of failed DNS resolutions in current worker process since started"
      }
     ]
    },
    {
     "title": "Process - Pipes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 7260 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_max_pipes{job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "Hard limit on the number of pipes for splicing, 0=unlimited"
      },
      {
       "expr": "rate(haproxy_process_pipes_used_total{job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Used pipes"
      },
      {
       "expr": "rate(haproxy_process_pipes_free_total{job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Free pipes"
      }
     ]
    },
    {
     "title": "Process - Listeners",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 7260 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_listeners{job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "Current number of active listeners"
      }
     ]
    },
    {
     "title": "Process - Memory",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 7271 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "haproxy_process_max_memory_bytes{job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "Memory limit; 0=unset"
      },
      {
       "expr": "haproxy_process_pool_allocated_bytes{job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "Memory allocated in pools"
      },
      {
       "expr": "haproxy_process_pool_used_bytes{job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "Memory used in pools"
      }
     ]
    },
    {
     "title": "Process - Pool allocations",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 7271 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_process_pool_failures_total{job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Failed pool allocations"
      }
     ]
    },
    {
     "title": "Process - Jobs",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 7271 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_jobs{job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "Current number of active jobs (listeners, sessions, open devices)"
      },
      {
       "expr": "haproxy_process_unstoppable_jobs{job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "Current number of active jobs that can't be stopped during a soft stop"
      }
     ]
    },
    {
     "title": "Process - Configured Threads / Processes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 7282 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_nbthread{job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "Threads"
      },
      {
       "expr": "haproxy_process_nbproc{job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "Processes"
      }
     ]
    },
    {
     "title": "Process - Logs",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 7282 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_process_dropped_logs_total{job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total number of dropped logs"
      },
      {
       "expr": "rate(haproxy_process_recv_logs_total{job=\"commstack-haproxy\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total number of log messages received by log-forwarding listeners"
      }
     ]
    },
    {
     "title": "Process - Peers",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 7282 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_active_peers{job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "Active peers"
      },
      {
       "expr": "haproxy_process_connected_peers{job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "Connected peers"
      }
     ]
    },
    {
     "title": "Process - Tasks / Runqueue",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 7293 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_current_tasks{job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "Total number of tasks in the current worker process (active + sleeping)"
      },
      {
       "expr": "haproxy_process_current_run_queue{job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "Total number of active tasks+tasklets in the current worker process"
      }
     ]
    },
    {
     "title": "Process - Idle / Stopping",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 7293 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "haproxy_process_idle_time_percent{job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "Idle to total ratio over last sample (percent)"
      },
      {
       "expr": "haproxy_process_stopping{job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "Non zero means stopping in progress"
      }
     ]
    },
    {
     "title": "Process - Uptime",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 7293 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_process_uptime_seconds{job=\"commstack-haproxy\",instance=\"$host\"}",
       "legendFormat": "How long ago this worker process was started"
      }
     ]
    }
   ]
  }
 ]
}