{
 "title": "N42 Gateway",
 "description": "HAProxy Ingress dashboard",
 "tags": [
  "haproxy",
  "ingress-controller",
  "kubernetes"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(haproxy_frontend_sessions_total,cluster)"
    }
   },
   {
    "name": "hostname",
    "query": {
     "query": "label_values(haproxy_frontend_sessions_total{cluster=~\"$cluster\"},hostname)"
    }
   },
   {
    "name": "backend",
    "query": {
     "query": "label_values(haproxy_backend_sessions_total{cluster=~\"$cluster\",hostname=~\"$hostname\"},proxy)"
    }
   },
   {
    "name": "pub_front_exclude",
    "label": "controller version",
    "query": "v0.10-v0.13 : (_front__auth) , v0.10-v0.13 (with ssl-passthrough) : (_front__auth|_front_https) , v0.14+ : (.*__local)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HAProxy proc use",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rate(n42gateway_haproxy_processing_seconds_total{cluster=~\"$cluster\",hostname=~\"$hostname\"}[1m]))"
    }
   ]
  },
  {
   "title": "HAProxy running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(n42gateway_update_success{cluster=~\"$cluster\",hostname=~\"$hostname\"})-count(haproxy_process_start_time_seconds{job=\"n42-gateway\",cluster=~\"$cluster\",hostname=~\"$hostname\"})"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sum(haproxy_frontend_current_sessions{cluster=~\"$cluster\",hostname=~\"$hostname\"}) by (hostname)/max(haproxy_process_max_connections{cluster=~\"$cluster\",hostname=~\"$hostname\"}) by (hostname))"
    }
   ]
  },
  {
   "title": "Connection rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "conn/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_connections_total{cluster=~\"$cluster\",hostname=~\"$hostname\",proxy!~\"$pub_front_exclude\"}[1m]))"
    }
   ]
  },
  {
   "title": "HAProxy threads p/proc",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(haproxy_process_nbthread{cluster=~\"$cluster\",hostname=~\"$hostname\"}) / count(haproxy_process_nbthread{cluster=~\"$cluster\",hostname=~\"$hostname\"})"
    }
   ]
  },
  {
   "title": "HAProxy uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-max(haproxy_process_start_time_seconds{job=\"n42-gateway\",cluster=~\"$cluster\",hostname=~\"$hostname\"})"
    }
   ]
  },
  {
   "title": "Reload successful",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-min(n42gateway_update_success{cluster=~\"$cluster\",hostname=~\"$hostname\"})"
    }
   ]
  },
  {
   "title": "Certificate expiring",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "days" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(min(n42gateway_cert_expire_date_epoch)-time())/3600/24"
    }
   ]
  },
  {
   "title": "HTTP request rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_http_responses_total{cluster=~\"$cluster\",hostname=~\"$hostname\",proxy!~\"_front__auth.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Controller instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(n42gateway_update_success{cluster=~\"$cluster\",hostname=~\"$hostname\"})"
    }
   ]
  },
  {
   "title": "Controller uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-max(process_start_time_seconds{cluster=~\"$cluster\",hostname=~\"$hostname\"})"
    }
   ]
  },
  {
   "title": "HAProxy process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "HAProxy process use",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(n42gateway_haproxy_processing_seconds_total{cluster=~\"$cluster\",hostname=~\"$hostname\"}[1m])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Admin socket response time",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(n42gateway_haproxy_response_time_seconds_sum{cluster=~\"$cluster\",hostname=~\"$hostname\",command=\"show_info\"}[1m])/rate(n42gateway_haproxy_response_time_seconds_count{cluster=~\"$cluster\",hostname=~\"$hostname\",command=\"show_info\"}[1m])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Full reloads (1m)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(n42gateway_updates_total{cluster=~\"$cluster\",hostname=~\"$hostname\",status=\"full\"}[1m])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Admin socket response time above 10ms",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1-(increase(n42gateway_haproxy_response_time_seconds_bucket{cluster=~\"$cluster\",hostname=~\"$hostname\",command=\"show_info\",le=\"0.01\"}[1m]) / ignoring (le) increase(n42gateway_haproxy_response_time_seconds_count{cluster=~\"$cluster\",hostname=~\"$hostname\",command=\"show_info\"}[1m]))",
       "legendFormat": "{{hostname}}"
      }
     ]
    }
   ]
  },
  { "title": "Controller process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{cluster=~\"$cluster\",hostname=~\"$hostname\",job=\"n42-gateway\"}[1m])",
     "legendFormat": "{{hostname}} | {{job}}"
    }
   ]
  },
  {
   "title": "Controller sync rate (1m)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(n42gateway_updates_total{cluster=~\"$cluster\",hostname=~\"$hostname\"}[1m])) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Frontend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connection rate",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "conn/s" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_frontend_connections_total{cluster=~\"$cluster\",hostname=~\"$hostname\",proxy!~\"$pub_front_exclude\"}[1m])) by (hostname)",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "HTTP request/response rate",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_frontend_http_responses_total{cluster=~\"$cluster\",hostname=~\"$hostname\",proxy!~\"_front__auth.*\"}[1m])) by (hostname)",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Active sessions",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(haproxy_frontend_current_sessions{cluster=~\"$cluster\",hostname=~\"$hostname\"}) by (hostname)",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Active sessions / max",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(haproxy_frontend_current_sessions{cluster=~\"$cluster\",hostname=~\"$hostname\"}) by (hostname)/min(haproxy_process_max_connections{cluster=~\"$cluster\",hostname=~\"$hostname\"}) by (hostname)",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Cluster wide throughput",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_frontend_bytes_in_total{cluster=~\"$cluster\",hostname=~\"$hostname\",proxy!~\"$pub_front_exclude\"}[1m]))",
       "legendFormat": "in"
      },
      {
       "expr": "-sum(rate(haproxy_frontend_bytes_out_total{cluster=~\"$cluster\",hostname=~\"$hostname\",proxy!~\"$pub_front_exclude\"}[1m]))",
       "legendFormat": "out"
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_frontend_bytes_in_total{cluster=~\"$cluster\",hostname=~\"$hostname\",proxy!~\"$pub_front_exclude\"}[1m])) by (hostname)",
       "legendFormat": "{{hostname}} in"
      },
      {
       "expr": "-sum(rate(haproxy_frontend_bytes_out_total{cluster=~\"$cluster\",hostname=~\"$hostname\",proxy!~\"$pub_front_exclude\"}[1m])) by (hostname)",
       "legendFormat": "{{hostname}} out"
      }
     ]
    }
   ]
  },
  {
   "title": "Backend response failures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 4xx responses (1m)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5,sum(increase(haproxy_backend_http_responses_total{cluster=~\"$cluster\",hostname=~\"$hostname\",proxy=~\"$backend\",code=\"4xx\"}[1m])) by (proxy,code))",
       "legendFormat": "{{code}} - {{proxy}}"
      }
     ]
    },
    {
     "title": "Top 5 5xx responses (1m)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5,sum(increase(haproxy_backend_http_responses_total{cluster=~\"$cluster\",hostname=~\"$hostname\",proxy=~\"$backend\",code=~\"5xx|other\"}[1m])) by (proxy,code))",
       "legendFormat": "{{code}} - {{proxy}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backend status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 request/response rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "topk(5,sum(rate(haproxy_backend_http_responses_total{cluster=~\"$cluster\",hostname=~\"$hostname\",proxy=~\"$backend\"}[1m])) by (proxy))",
       "legendFormat": "{{proxy}}"
      }
     ]
    },
    {
     "title": "Top 5 throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk(5,sum(rate(haproxy_backend_bytes_in_total{cluster=~\"$cluster\",hostname=~\"$hostname\",proxy=~\"$backend\"}[1m])) by (proxy))",
       "legendFormat": "{{proxy}} in"
      },
      {
       "expr": "-topk(5,sum(rate(haproxy_backend_bytes_out_total{cluster=~\"$cluster\",hostname=~\"$hostname\",proxy=~\"$backend\"}[1m])) by (proxy))",
       "legendFormat": "{{proxy}} out"
      }
     ]
    },
    {
     "title": "Top 5 max connection time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(5,max(haproxy_backend_connect_time_average_seconds{cluster=~\"$cluster\",hostname=~\"$hostname\",proxy=~\"$backend\"}) by (proxy))",
       "legendFormat": "{{proxy}}"
      }
     ]
    },
    {
     "title": "Top 5 active sessions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5,sum(haproxy_backend_current_sessions{cluster=~\"$cluster\",hostname=~\"$hostname\",proxy=~\"$backend\"}) by (proxy))",
       "legendFormat": "{{proxy}}"
      }
     ]
    }
   ]
  },
  { "title": "Certificates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Certificate expiration",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "min(1000*n42gateway_cert_expire_date_epoch{cluster=~\"$cluster\",hostname=~\"$hostname\"}) by (cn)"
    }
   ]
  },
  {
   "title": "New certificates issued",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(n42gateway_cert_signing_count{cluster=~\"$cluster\",hostname=~\"$hostname\",reason=\"missing\",success=\"true\"}[1m])) by (hostname)",
     "legendFormat": "{{hostname}} | missing"
    },
    {
     "expr": "sum(increase(n42gateway_cert_signing_count{cluster=~\"$cluster\",hostname=~\"$hostname\",reason=\"expiring\",success=\"true\"}[1m])) by (hostname)",
     "legendFormat": "{{hostname}} | expiring"
    },
    {
     "expr": "sum(increase(n42gateway_cert_signing_count{cluster=~\"$cluster\",hostname=~\"$hostname\",reason=\"outdated\",success=\"true\"}[1m])) by (hostname)",
     "legendFormat": "{{hostname}} | outdated"
    }
   ]
  },
  {
   "title": "Certificate signing failures",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(n42gateway_cert_signing_count{cluster=~\"$cluster\",hostname=~\"$hostname\",success=\"false\"}[1m])) by (hostname,domains)",
     "legendFormat": "{{hostname}} | {{domains}}"
    }
   ]
  }
 ]
}