apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-root
  namespace: minio
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameterstore
    kind: ClusterSecretStore
  target:
    name: minio-root
    template:
      data:
        rootUser: "root"
        rootPassword: "{{`{{ .minio_root_password | toString }}`}}"
  data:
  - secretKey: minio_root_password
    remoteRef:
      key: "/{{ .Values.environment }}-infra-bedrock/minio_root_password"
