apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-users
  namespace: minio
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameterstore
    kind: ClusterSecretStore
  target:
    name: minio-users
    template:
      data:
        adminPassword: "{{`{{ .minio_user_admin_password | toString }}`}}"
        argoWorkflowsArtifactRepositoryPassword: "{{`{{ .minio_user_artifact_repository_password | toString }}`}}"
        harborPassword: "{{`{{ .minio_user_harbor_password | toString }}`}}"
        goldenImagesPassword: "{{`{{ .minio_user_golden_images_password | toString }}`}}"
        firmwarePassword: "{{`{{ .minio_user_firmware_password | toString }}`}}"
        plannedPhasePassword: "{{`{{ .minio_user_planned_phase_password | toString }}`}}"
  data:
  - secretKey: minio_user_admin_password
    remoteRef:
      key: "/{{ .Values.environment }}-infra-bedrock/minio_user_admin_password"
  - secretKey: minio_user_artifact_repository_password
    remoteRef:
      key: "/{{ .Values.environment }}-infra-bedrock/minio_user_artifact_repository_password"
  - secretKey: minio_user_harbor_password
    remoteRef:
      key: "/{{ .Values.environment }}-infra-bedrock/minio_user_harbor_password"
  - secretKey: minio_user_golden_images_password
    remoteRef:
      key: "/{{ .Values.environment }}-infra-bedrock/minio_user_golden_images_password"
  - secretKey: minio_user_firmware_password
    remoteRef:
      key: "/{{ .Values.environment }}-infra-bedrock/minio_user_firmware_password"
  - secretKey: minio_user_planned_phase_password
    remoteRef:
      key: "/{{ .Values.environment }}-infra-bedrock/minio_user_planned_phase_password"
