apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-admin
  namespace: minio
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: minio-admin
  data:
  - secretKey: password
    remoteRef:
      key: "/{{ .Values.environment }}/minio_admin"
      property: password
