apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: client-info-secret
  namespace: synology-csi
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: client-info-secret
    template:
      data:
        client-info.yaml:
          clients:
            host: "{{ `{{ .address }}` }}"
            https: "true"
            password: "{{ `{{ .password }}` }}"
            port: "5001"
            username: "{{ `{{ .username }}` }}"
  data:
    - secretKey: username
      remoteRef:
        key: "{{ .Values.environment }}/synology-csi"
        property: username
    - secretKey: password
      remoteRef:
        key: "{{ .Values.environment }}/synology-csi"
        property: password
    - secretKey: address
      remoteRef:
        key: "{{ .Values.environment }}/synology-csi"
        property: address
