apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cachyos-mirror-syncthing-certs
  namespace: cachyos-mirror
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: cachyos-mirror-syncthing-certs
    template:
      data:
        cert.pem: "{{ `{{ .cert }}` }}"
        key.pem: "{{ `{{ .key }}` }}"
  data:
    - secretKey: cert
      remoteRef:
        key: "/cachyos_mirror"
        property: syncthing_cert
    - secretKey: key
      remoteRef:
        key: "/cachyos_mirror"
        property: syncthing_key
