apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-s3-credentials
  namespace: vault
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameterstore
    kind: ClusterSecretStore
  target:
    name: vault-s3-credentials
    template:
      data:
        credentials: |
          [default]
            aws_access_key_id="{{`{{ .vault_aws_access_key_id | toString }}`}}"
            aws_secret_access_key="{{`{{ .vault_aws_secret_access_key | toString }}`}}"
  data:
  - secretKey: vault_aws_access_key_id
    remoteRef:
      key: "/{{ .Values.environment }}-generic/vault_aws_access_key_id"
  - secretKey: vault_aws_secret_access_key
    remoteRef:
      key: "/{{ .Values.environment }}-generic/vault_aws_secret_access_key"
