apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-repo
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: argocd-repo-{{ .Values.environment }}
    creationPolicy: Merge
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: "git"
        url: "{{ `{{ .url }}` }}"
        name: "{{ `{{ .name }}` }}"
        username: "{{ `{{ .username }}` }}"
        password: "{{ `{{ .password }}` }}"
  data:
    - secretKey: url
      remoteRef:
        key: "/{{ .Values.environment }}/github"
        property: repo
    - secretKey: name
      remoteRef:
        key: "/{{ .Values.environment }}/github"
        property: repo_name
    - secretKey: username
      remoteRef:
        key: "/{{ .Values.environment }}/github"
        property: username
    - secretKey: password
      remoteRef:
        key: "/{{ .Values.environment }}/github"
        property: token
