apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-admin
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: argocd-secret
    creationPolicy: Merge
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
      data:
        admin.password: "{{ `{{ .admin_password }}` }}"
  data:
    - secretKey: admin_password
      remoteRef:
        key: "/{{ .Values.environment }}/argocd"
        property: admin_password
