{
 "title": "Hubble Metrics and Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "General Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Flows processed Per Node",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(sum(rate(hubble_flows_processed_total[1m])) by (pod))",
     "legendFormat": "avg"
    },
    {
     "expr": "min(sum(rate(hubble_flows_processed_total[1m])) by (pod))",
     "legendFormat": "min"
    },
    {
     "expr": "max(sum(rate(hubble_flows_processed_total[1m])) by (pod))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Flows Types",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_processed_total[1m])) by (pod, type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "L7 Flow Distribution",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_processed_total{type=\"L7\"}[1m])) by (pod, subtype)",
     "legendFormat": "{{subtype}}"
    }
   ]
  },
  {
   "title": "Trace Flow Distribution",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_processed_total{type=\"Trace\"}[1m])) by (pod, subtype)",
     "legendFormat": "{{subtype}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Forwarded vs Dropped",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_processed_total[1m])) by (pod, verdict)",
     "legendFormat": "{{verdict}}"
    }
   ]
  },
  {
   "title": "Drop Reason",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_drop_total[1m])) by (pod, reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Protocol Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum (rate(hubble_port_distribution_total[1m])) by (pod, protocol)",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Top 10 Port Distribution",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "topk(10, sum (rate(hubble_port_distribution_total{port!=\"0\"}[1m])) by (pod, port, protocol))",
     "legendFormat": "{{port}}/{{protocol}}"
    }
   ]
  },
  {
   "title": "TCPv4",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_tcp_flags_total{family=\"IPv4\"}[1m])) by (pod, flag)",
     "legendFormat": "{{flag}}"
    }
   ]
  },
  {
   "title": "Missing TCPv4 SYN-ACKs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_tcp_flags_total{family=\"IPv4\", flag=\"SYN\"}[1m])) by (pod) - sum(rate(hubble_tcp_flags_total{family=\"IPv4\", flag=\"SYN-ACK\"}[1m])) by (pod)",
     "legendFormat": "Missing SYN-ACK"
    }
   ]
  },
  {
   "title": "TCPv6",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_tcp_flags_total{family=\"IPv6\"}[1m])) by (pod, flag)",
     "legendFormat": "{{flag}}"
    }
   ]
  },
  {
   "title": "Missing TCPv6 SYN-ACKs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_tcp_flags_total{family=\"IPv6\", flag=\"SYN\"}[1m])) by (pod) - sum(rate(hubble_tcp_flags_total{family=\"IPv6\", flag=\"SYN-ACK\"}[1m])) by (pod)",
     "legendFormat": "Missing SYN-ACK"
    }
   ]
  },
  {
   "title": "ICMPv4",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_icmp_total{family=\"IPv4\"}[1m])) by (pod, type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Missing ICMPv4 Echo-Reply",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_icmp_total{family=\"IPv4\", type=\"EchoRequest\"}[1m])) by (pod) - sum(rate(hubble_icmp_total{family=\"IPv4\", type=\"EchoReply\"}[1m])) by (pod)",
     "legendFormat": "Missing ICMP Echo-Reply"
    }
   ]
  },
  {
   "title": "ICMPv6",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_icmp_total{family=\"IPv6\"}[1m])) by (pod, type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Missing ICMPv6 Echo-Reply",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_icmp_total{family=\"IPv6\", type=\"EchoRequest\"}[1m])) by (pod) - sum(rate(hubble_icmp_total{family=\"IPv6\", type=\"EchoReply\"}[1m])) by (pod)",
     "legendFormat": "Missing ICMP Echo-Reply"
    }
   ]
  },
  { "title": "Network Policy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Denies by Reason",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_drop_total{reason=\"POLICY_DENIED\"}[1m])) by (pod, reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Denied Packets by Protocol",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_drop_total{reason=\"POLICY_DENIED\"}[1m])) by (pod, protocol)",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Top 10 Source Pods with Denied Packets",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(hubble_drop_total{reason=\"POLICY_DENIED\"}[1m])) by (pod, source))",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Top 10 Destination Pods with Denied Packets",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(hubble_drop_total{reason=\"POLICY_DENIED\"}[1m])) by (pod, destination))",
     "legendFormat": "{{destination}}"
    }
   ]
  }
 ]
}