apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-key
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-key
  data:
  - secretKey: api_key
    remoteRef:
      key: "/{{ .Values.environment }}/cloudflare_api_key"
      property: api_key
