apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-key
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-key
    template:
      data:
        api-key: "{{`{{ .api-key | toString }}`}}"
  data:
  - secretKey: api-key
    remoteRef:
      key: "/{{ .Values.environment }}/cloudflare-api-key"
      property: "api-key"
