apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hetzner-api-token
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: hetzner-api-token
  data:
    - secretKey: api-key
      remoteRef:
        key: "/hetzner"
        property: api_token
