---
replicaCount: 1

image:
  repository: nginx
  tag: 1.28.2-alpine
  pullPolicy: IfNotPresent

sync:
  image:
    repository: ghcr.io/ironashram/toolbox
    tag: v3.0.14
  upstream: rsync://nl.mirror.cx/cachyos/
  schedule: "0 */6 * * *"

storage:
  size: 250Gi
  storageClass: ""
  accessMode: ReadWriteOnce
  excludeFromBackup: false

service:
  port: 80

ingress:
  enabled: true
  className: haproxy
  host: ""
  tls:
    enabled: true
    secretName: cachyos-mirror-cert
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

extraIngresses: []

nodeSelector: {}

resources:
  nginx:
    requests:
      cpu: 50m
      memory: 64Mi
  sync:
    requests:
      cpu: 100m
      memory: 128Mi
