apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.letsencrypt.email }}
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: m1k.cloud@outlook.com
            apiTokenSecretRef:
              name: {{ .Values.letsencrypt.existingSecret.name }}
              key: {{ .Values.letsencrypt.existingSecret.key }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.letsencrypt.email }}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudflare:
            email: m1k.cloud@outlook.com
            apiTokenSecretRef:
              name: {{ .Values.letsencrypt.existingSecret.name }}
              key: {{ .Values.letsencrypt.existingSecret.key }}
