apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ include "letsencrypt.email" . }}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          webhook:
            groupName: {{ include "letsencrypt.groupName" . }}
            solverName: hetzner
            config:
              secretName: {{ .Values.letsencrypt.existingSecret.name }}
              zoneName: {{ include "letsencrypt.zoneName" . }}
              apiUrl: {{ .Values.letsencrypt.apiUrl | default "https://dns.hetzner.com/api/v1" }}
