apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: { { .Values.letsencrypt.email } }
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          webhook:
            groupName: { { .Values.letsencrypt.groupName } }
            solverName: hetzner
            config:
              secretName: { { .Values.letsencrypt.existingSecret.name } }
              zoneName: { { .Values.letsencrypt.zoneName } }
              apiUrl: https://dns.hetzner.com/api/v1
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: { { .Values.letsencrypt.email } }
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          webhook:
            groupName: { { .Values.letsencrypt.groupName } }
            solverName: hetzner
            config:
              secretName: { { .Values.letsencrypt.existingSecret.name } }
              zoneName: { { .Values.letsencrypt.zoneName } }
              apiUrl: https://dns.hetzner.com/api/v1
