apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ include "letsencrypt.email" . }}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          webhook:
            groupName: {{ include "letsencrypt.groupName" . }}
            solverName: hetzner
            config:
              tokenSecretKeyRef:
                name: {{ .Values.letsencrypt.existingSecret.name }}
                key: api-key
