apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-config-secret
  namespace: arc-runners
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: github-config-secret
    template:
      data:
        github_token: "{{ `{{ .token }}` }}"
  data:
    - secretKey: token
      remoteRef:
        key: "/arc_runners"
        property: github_token
