apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kub1k-kubeconfig
  namespace: arc-runners
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: kub1k-kubeconfig
    template:
      data:
        kubeconfig: "{{ `{{ .kubeconfig }}` }}"
  data:
    - secretKey: kubeconfig
      remoteRef:
        key: "/arc_runners"
        property: kubeconfig
        decodingStrategy: base64
