name: "ArgoCD App Updates"

on:
  schedule:
    - cron: "23 6 */3 * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: "0"

      - name: Check updates for ArgoCD Apps
        uses: ironashram/argocd-apps-action@7060961aa8654bc747a373177a9d8c43c2ab7a03 # v3.2.0
        with:
          skip_prerelease: true
          target_branch: main
          create_pr: true
          labels: "helm,argocd"
          apps_folder: apps/templates
          allow_regex_fallback: true
          delete_superseded_branches: true
          check_image_pins: true
          token: ${{ secrets.ACTION_TOKEN }}
