name: "ArgoCD App Updates"

on:
  schedule:
    - cron: '0 6 * * 6'
  workflow_dispatch:

jobs:

  update:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        pull-requests: write
    steps:

      - name: Check out
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: '0'

      - name: Check updates for ArgoCD Apps
        uses: ironashram/argocd-apps-action@975c24ecd3ee2b18a419e734a29932348521a4bb # v2.2.0
        with:
          skip_prerelease: true
          target_branch: main
          create_pr: true
          apps_folder: apps/templates
          allow_regex_fallback: true
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
