name: Terraform Plan

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'terraform/**'
      - 'terraform/**/*.yaml'

jobs:
  plan:
    runs-on: gha-runner-scale-set-kub1k
    container:
      image: quay.io/m1k_cloud/toolbox:latest
    defaults:
      run:
        shell: bash
    permissions:
      contents: read
      pull-requests: write

    name: Create terraform plan
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up ssh key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent)
          ssh-add -q ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: terraform plan
        run: make plan kub1k
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
          TF_VAR_remote_state_s3_endpoint: ${{ secrets.TF_VAR_REMOTE_STATE_S3_ENDPOINT }}

      - name: Post plan as PR comment
        if: github.event_name == 'pull_request'
        run: make comment-pr kub1k
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload plan artifact
        if: github.event_name == 'pull_request'
        run: aws s3 cp terraform/terraform.tfplan s3://${S3_BUCKET}/${S3_PREFIX}/terraform.tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL:  ${{ secrets.AWS_ENDPOINT_URL }}
          S3_BUCKET: github-artifacts
          S3_PREFIX: ${{ github.event.repository.name }}/pulls/${{ github.event.number }}/terraform-plan
