name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  workflow_dispatch:

jobs:
  apply:
    runs-on: gha-runner-scale-set-kub1k
    container:
      image: quay.io/m1k_cloud/automation_docker_image:latest
    defaults:
      run:
        shell: bash
    permissions:
        contents: read
        pull-requests: write

    name: Apply approved plan
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform apply
        uses: dflook/terraform-apply@v1.44
        with:
          path: terraform
          workspace: kub1k
          auto_approve: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          TERRAFORM_PRE_RUN: |
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
            eval $(ssh-agent)
            ssh-add ~/.ssh/id_rsa
            mkdir -p ~/.kube/config-files
