name: Terraform Apply

on:
  pull_request:
    types: [closed]
    paths:
      - 'terraform/**'
      - 'terraform/**/*.yaml'

jobs:
  apply:
    runs-on: gha-runner-scale-set-kub1k
    container:
      image: quay.io/m1k_cloud/toolbox:latest
    defaults:
      run:
        shell: bash
    permissions:
      contents: read
      pull-requests: write

    name: Apply approved plan
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up ssh key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent)
          ssh-add -q ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Download plan artifact
        run: aws s3 cp s3://${S3_BUCKET}/${S3_PREFIX}/terraform.tfplan terraform/terraform.tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL:  ${{ secrets.AWS_ENDPOINT_URL }}
          S3_BUCKET: github-artifacts
          S3_PREFIX: ${{ github.event.repository.name }}/pulls/${{ github.event.number }}/terraform-plan

      - name: terraform apply
        run: make plan kub1k && make apply kub1k
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
          TF_VAR_remote_state_s3_endpoint: ${{ secrets.TF_VAR_REMOTE_STATE_S3_ENDPOINT }}
