name: Terraform Plan

on:
  pull_request:
    paths:
      - 'terraform/**'
  workflow_dispatch:

jobs:
  plan:
    runs-on: [self-hosted, linux, X64, default]
    permissions:
      contents: read
      pull-requests: write
    name: Create terraform plan
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get kubeconfig
        uses: dflook/terraform-output@v1
        id: get-kubeconfig
        with:
          path: terraform
          workspace: kub1k

      - name: Write kubeconfig
        run: |
          mkdir -p $GITHUB_WORKSPACE/.kube/config-files
          echo "${{ steps.get-kubeconfig.outputs.kubeconfig }}" > $GITHUB_WORKSPACE/.kube/config-files/kub1k.yaml

      - name: Print GitHub Workspace
        run: echo $GITHUB_WORKSPACE/.kube/config-files/kub1k.yaml

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: terraform
          workspace: kub1k
          variables: |
            GITHUB_WORKSPACE="${{ github.workspace }}"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
