name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  workflow_dispatch:

jobs:
  apply:
    runs-on: gha-runner-scale-set-kub1k
    permissions:
        contents: write
        pull-requests: write
    name: Apply approved plan
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install openssh-client
        run: |
          sudo apt-get update
          sudo apt-get install openssh-client -y

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: terraform
          workspace: kub1k
          auto_approve: true
        env:
          TERRAFORM_PRE_RUN: |
            curl -sSL https://github.com/alexellis/k3sup/releases/latest/download/k3sup > k3sup
            chmod +x k3sup
            mv k3sup /usr/local/bin/k3sup
            which python3
