name: Terraform Plan

on:
  pull_request:
    paths:
      - 'terraform/**'
      - 'terraform/**/*.yaml'
  workflow_dispatch:

jobs:
  plan:
    runs-on: gha-runner-scale-set-kub1k
    container:
      image: quay.io/m1k_cloud/automation_docker_image:latest
    defaults:
      run:
        shell: bash
    permissions:
      contents: read
      pull-requests: write

    name: Create terraform plan
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform plan
        uses: dflook/terraform-plan@v1.45
        with:
          path: terraform
          workspace: kub1k
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          TERRAFORM_PRE_RUN: |
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
            eval $(ssh-agent)
            ssh-add ~/.ssh/id_rsa
            mkdir -p ~/.kube/config-files
