name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  workflow_dispatch:

jobs:
  apply:
    runs-on: [self-hosted, linux, X64, default]
    permissions:
        contents: write
        pull-requests: write
    name: Apply approved plan
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.4

      - name: Get kubeconfig
        run: |
          make get-kubeconfig kub1k

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: terraform
          workspace: kub1k
