name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  workflow_dispatch:

jobs:
  apply:
    runs-on: gha-runner-scale-set-kub1k
    permissions:
        contents: write
        pull-requests: write
    name: Apply approved plan
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: terraform
          workspace: kub1k
        env:
          TERRAFORM_PRE_RUN: |
            curl -sLS https://get.k3sup.dev | sh
            install k3sup /usr/local/bin/

