apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
    - port: metrics
      interval: 60s
      metricRelabelings:
        - action: labeldrop
          regex: "instance|pod"
  selector:
    matchLabels:
      app: {{ .Release.Name }}
